/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AdminStocksRouteImport } from './routes/admin-stocks'
import { Route as AdminUsersRouteImport } from './routes/admin-users'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MyStocksRouteImport } from './routes/my-stocks'
import { Route as OptionChainRouteImport } from './routes/option-chain'
import { Route as SettingsRouteImport } from './routes/settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStocksRoute = AdminStocksRouteImport.update({
  id: '/admin-stocks',
  path: '/admin-stocks',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin-users',
  path: '/admin-users',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MyStocksRoute = MyStocksRouteImport.update({
  id: '/my-stocks',
  path: '/my-stocks',
  getParentRoute: () => rootRouteImport,
} as any)
const OptionChainRoute = OptionChainRouteImport.update({
  id: '/option-chain',
  path: '/option-chain',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/admin-stocks': typeof AdminStocksRoute
  '/admin-users': typeof AdminUsersRoute
  '/login': typeof LoginRoute
  '/my-stocks': typeof MyStocksRoute
  '/option-chain': typeof OptionChainRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/admin-stocks': typeof AdminStocksRoute
  '/admin-users': typeof AdminUsersRoute
  '/login': typeof LoginRoute
  '/my-stocks': typeof MyStocksRoute
  '/option-chain': typeof OptionChainRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/admin-stocks': typeof AdminStocksRoute
  '/admin-users': typeof AdminUsersRoute
  '/login': typeof LoginRoute
  '/my-stocks': typeof MyStocksRoute
  '/option-chain': typeof OptionChainRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/admin-stocks'
    | '/admin-users'
    | '/login'
    | '/my-stocks'
    | '/option-chain'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/admin-stocks'
    | '/admin-users'
    | '/login'
    | '/my-stocks'
    | '/option-chain'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-login'
    | '/admin-stocks'
    | '/admin-users'
    | '/login'
    | '/my-stocks'
    | '/option-chain'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminStocksRoute: typeof AdminStocksRoute
  AdminUsersRoute: typeof AdminUsersRoute
  LoginRoute: typeof LoginRoute
  MyStocksRoute: typeof MyStocksRoute
  OptionChainRoute: typeof OptionChainRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-stocks': {
      id: '/admin-stocks'
      path: '/admin-stocks'
      fullPath: '/admin-stocks'
      preLoaderRoute: typeof AdminStocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-users': {
      id: '/admin-users'
      path: '/admin-users'
      fullPath: '/admin-users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-stocks': {
      id: '/my-stocks'
      path: '/my-stocks'
      fullPath: '/my-stocks'
      preLoaderRoute: typeof MyStocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/option-chain': {
      id: '/option-chain'
      path: '/option-chain'
      fullPath: '/option-chain'
      preLoaderRoute: typeof OptionChainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminStocksRoute: AdminStocksRoute,
  AdminUsersRoute: AdminUsersRoute,
  LoginRoute: LoginRoute,
  MyStocksRoute: MyStocksRoute,
  OptionChainRoute: OptionChainRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
